### ISSUE TITLE
Empty Results List

### ISSUE THREAD

**Issue by panushri25** [Georgetown-IR-Lab/QuickUMLS#11] opened 2018-01-28 21:26 UTC
Hi,

I installed QuickUMLS as directed, no errors in the process. When I run the API on a text in python, the result list returned is always empty.

python version = 2.7
GetUMLS version = 1.2.1
UMLS2017AB-full

Please help.

Thank you,
Anusri

**Comment by soldni** [comment] 2018-01-28 21:34
Anusri,

Could you give me a bit more context about your setup? e.g. python version, OS version, UMLS installation details, etc. Also, are you using the straight API or are you using QuickUMLS in client/server mode?

**Comment by soldni** [comment] 2018-01-30 02:46
I can't seem to reproduce this issue on my end -- could you check if your UMLS installation folder contains a MRCONSO.RRF and MRREF.RRF files (and how big they are?)

**Comment by panushri25** [comment] 2018-01-30 02:56
MRCONSO.RRF is 858.2 MB and MRSTY.RRF is 166.4 MB. These were the important files needed as mentioned ?

I dont see a MRREF.RRF , but instead there is a MRREL.RRF (2.3GB).

**Comment by soldni** [comment] 2018-01-31 03:19
Would you mind trying with Python 3. I couldn't reproduce the issue with python 2 either, but I'm trying to narrow down options. Also, what are the contents of `home/anusri/Desktop/IBM/GetUMLS/QuickUMLS/new/`? It should have the following structure:
```
├── cui-semtypes.db
│   ├── cui.leveldb
│   └── semtypes.leveldb
└── umls-simstring.db
```

**Comment by panushri25** [comment] 2018-01-31 04:49
Yes that was the file structure in QuickUMLS/new/. I tried the python 3 version, its working. Thanks a lot :)

I notice one difference, hope it will help you debug the next time. The cui.leveldb  and semtypes.leveldb are empty on my python2 version of installation, where as the python3 version of my installation these folder are loaded with a bunch of umls-terms.simstring.* files. I don't know why the installation was not successful when I used python2,  I will try to figure out and let you know if I find something.

**Comment by celinethi** [comment] 2020-07-23 08:51
Hi , I have just installed quickumls and facing the same issue. 

python: 3.7
macOS Catalina 10.15.4

UMLS installation : 
* 2020AA
* in 2020AA/META I have MRCONSO.RRF (27M), MRSTY.RRF(6.2M) and MRREL.RRF(217M) files but no MRREF.RRF file. I also have many other files like MRXW_FRE.RRF because I selected french datasets during installation

quickumls : 1.4.0 
* I tried installing it with EN and FRE language options (both SpaCy are installed)
* my umls_dir has the structure you mention above as and cui.leveldb and semtypes.leveldb directories are not empty

I tried launching this python script using the straight API : 

''' from quickumls import QuickUMLS
matcher = QuickUMLS('umls_dir')
text = "cell"
print(matcher.match(text, best_match=True, ignore_syntax=False)) '''

And it always returns an empty list. 

Did you find any solution to this issue ? When installing UMLS should I select a default installation instead of selecting specific terminologies ? To get the MRREF file ? 

Thank you, 

Céline

**Comment by soldni** [comment] 2020-07-25 21:31
Hi Celine, 

Sorry for the late reply! 

What concept are you expect "cell" to match? With default UMLS installation, "cell" is not matched. If I run `print(matcher.match('blood', best_match=True, ignore_syntax=False))`, I receive the following concepts

```
[[{'start': 0,
   'end': 4,
   'ngram': 'nose',
   'term': 'nose',
   'cui': 'C0028429',
   'similarity': 1.0,
   'semtypes': {'T023'},
   'preferred': 0}],
 [{'start': 0,
   'end': 4,
   'ngram': 'nose',
   'term': 'nose',
   'cui': 'C0028429',
   'similarity': 1.0,
   'semtypes': {'T023'},
   'preferred': 0}]]
```

So I would say that the behavior you are experiencing seem normal, unless there's a specific concept in your UMLS installation you're expecting to match. 

-Luca

**Comment by celinethi** [comment] 2020-07-27 14:14
Thank you for your answer ! You are right, I was not clear which was my UMLS installation. So I installed it again with default parameters to make some tests and it works. 

Thank you

Céline

**Comment by soldni** [comment] 2020-07-27 17:37
great to hear! closing this issue.

**Closed by soldni** 2020-07-27 17:37 UTC
