### ISSUE TITLE
Bug in version 1.2.2 using _is_ok_semtype

### ISSUE THREAD

**Issue by slbayer** [Georgetown-IR-Lab/QuickUMLS#14] opened 2018-02-28 17:43 UTC
The logic for _is_ok_semtype is wrong in quickumls.py. The list of accepted semtypes is used to determine whether a list of semtypes that the lookup procedure produces is acceptable, but it's basically an intersection with the list of accepted semtypes; if some of the semtypes in the target list are NOT in the list of accepted semtypes, they're not filtered out. A better implementation would be simply to intersect the two lists, and if the intersection is empty, discard the match, and if it's not, use the intersection.

**Comment by soldni** [comment] 2018-03-05 03:20
If I understand it correctly, this is by design. If a concept is associated with any of the accepted semantic types, it is returned as a valid match, even if it is also associated with an invalid semantic type.

**Comment by slbayer** [comment] 2018-03-05 15:16
It seems pretty odd to me for this to be the intended behavior. When QuickUMLS is initialized, you can give it a list of "accepted_semtypes". That seems to me to imply, pretty strongly, that the only semtypes which are returned will be in that list. If the implemented behavior is the intended one, it should at least be documented, because it's kind of counterintuitive.

**Comment by soldni** [comment] 2018-03-05 15:52
The problem is that many medical terms are associated with more that one semantic type. For example, consider `progesterone`. According to UMLS, it is associated with three semantic types: `
Organic Chemical (T109)`, `Hormone (T125)`, and `Pharmacologic Substance (T121)`. 

Let's say I am building an application that leverage mentions of drugs in text. If I am using QuickUMLS to find possible candidates, and restrict the available semantic types to `T121` only. In that case, I'd still like to retrieve any mention of `progesterone`, as it might be a likely candidate.

I agree that the documentation should be update to mention that the tool favors recall over precision in cases of polysemy.

**Comment by soldni** [comment] 2018-03-20 14:08
closed this issue for now -- will open again if necessary.

**Closed** 2018-03-20 14:07 UTC
