### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by hongjuny** [Georgetown-IR-Lab/QuickUMLS#20] opened 2018-07-16 16:44 UTC
I am struggling with "Too many open files" issue while processing 300,000+ documents on Python 2.7, presumably issue with multiprocessing. Would you please guide me what would be an easy way to fix? Thank you.

**Comment by soldni** [comment] 2018-07-16 20:11
Number of files being processed is not an issue; The problem is that the number of file descriptors allowed by your OS installation is too low for simstring (the library QuickUMLS uses under the hood for fuzzy matching); the fix for this issue is outside the scope of this project, but I recommend you to Google *"too many open files <name of your os>"* .

**Closed by soldni** 2018-07-16 20:11 UTC
